In [26]:
# Simple Logistic Regression on Iris Dataset with Parameters and Report
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, f1_score
import pandas as pd

# Define Parameters
params = {
    'test_size': 0.2,
    'random_state': 42,
    'max_iter': 100000,
    'solver': 'lbfgs',
    'multi_class': 'auto'
}

# Load data
iris = load_iris()
X, y = iris.data, iris.target

# Split data using defined parameters
X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=params['test_size'], 
    random_state=params['random_state']
)

# Train model with defined parameters
model = LogisticRegression(
    random_state=params['random_state'],
    max_iter=params['max_iter'],
    solver=params['solver'],
    multi_class=params['multi_class']
)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Create report variable with classification report
report = classification_report(y_test, y_pred, target_names=iris.target_names,output_dict=True)


print(f"\n=== MODEL PERFORMANCE ===")
print(f"Accuracy: {accuracy:.4f}")

print(f"\n=== CONFUSION MATRIX ===")
print(conf_matrix)

print(f"\n=== CLASSIFICATION REPORT ===")
print(report)



=== MODEL PERFORMANCE ===
Accuracy: 1.0000

=== CONFUSION MATRIX ===
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

=== CLASSIFICATION REPORT ===
{np.str_('setosa'): {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 10.0}, np.str_('versicolor'): {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 9.0}, np.str_('virginica'): {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 11.0}, 'accuracy': 1.0, 'macro avg': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 30.0}, 'weighted avg': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 30.0}}


c:\Users\aayush.verma\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


In [27]:
import mlflow


In [28]:
report_dict=report


In [29]:
mlflow.set_experiment("Iris Logistic Regression")
mlflow.set_tracking_uri("http://127.0.0.1:5000/")

with mlflow.start_run():
    # Log parameters
    mlflow.log_params(params)
    
    # Log scalar metrics only
    mlflow.log_metrics({
        'accuracy': report_dict['accuracy'],
        'precision_macro': report_dict['macro avg']['precision'],
        'recall_macro': report_dict['macro avg']['recall'],
        'f1_score_macro': report_dict['macro avg']['f1-score'],
        'precision_weighted': report_dict['weighted avg']['precision'],
        'recall_weighted': report_dict['weighted avg']['recall'],
        'f1_score_weighted': report_dict['weighted avg']['f1-score']
    })
    mlflow.sklearn.log_model(model, "LogisticRegression")
    
   

2025/10/03 14:14:30 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/10/03 14:14:42 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.


🏃 View run stylish-fish-797 at: http://127.0.0.1:5000/#/experiments/988989744012044841/runs/d1ae33e2c3b0464bae8c0461a57b0fe5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/988989744012044841
